baseURL = "https://listepilz.at/"
languageCode = "de_DE"
title = "Liste Pilz. Ja es geht!"
disableKinds = ["taxonomy","taxonomyTerm"]
GoogleAnalytics = "UA-103577542-1"

[[menu.footer]]
    name = "Impressum"
    weight = -110
    identifier = "impressum"
    url = "/impressum/index.html"

[[menu.footer]]
    name = "Presse"
    weight = -100
    identifier = "presse"
    url = "/presse/index.html"
