baseURL = "https://listepilz.at/"
languageCode = "de_DE"
title = "Liste Pilz. Ja es geht!"
GoogleAnalytics = "UA-103577542-1"


[[menu.footer]]
    name = "Kontakt"
    weight = -3
    identifier = "kontakt"
    url = "/kontakt"

[[menu.footer]]
    name = "Presse"
    weight = -2
    identifier = "presse"
    url = "/presse"

[[menu.footer]]
    name = "Impressum"
    weight = -1
    identifier = "impressum"
    url = "/impressum"

[taxonomies]
    liste = "listen"